# Generated by Django 3.1.7 on 2021-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(blank=True, help_text='اضف عنوان رئيسي', max_length=200, null=True, verbose_name='العنوان الرئيسي')),
                ('sub_header', models.TextField(blank=True, help_text='اضف عنوان ثانوي', null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'من نحن',
                'verbose_name_plural': 'من نحن',
            },
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'العناوين الاولية', 'verbose_name_plural': 'العناوين الاولية'},
        ),
        migrations.AlterField(
            model_name='header',
            name='main_header',
            field=models.CharField(blank=True, help_text='اضف عنوان رئيسي', max_length=200, null=True, verbose_name='العنوان الرئيسي'),
        ),
        migrations.AlterField(
            model_name='header',
            name='sub_header',
            field=models.TextField(blank=True, help_text='اضف عنوان ثانوي', null=True, verbose_name='الوصف'),
        ),
    ]
