# Generated by Django 3.1.7 on 2021-02-25 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0002_auto_20210225_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zulfiapp.header')),
            ],
        ),
    ]
