# Generated by Django 3.1.7 on 2021-02-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='celebrity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zulfiapp.header'),
        ),
    ]
