# Generated by Django 3.1.7 on 2021-02-25 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0004_auto_20210225_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='celebrity',
        ),
        migrations.AddField(
            model_name='image',
            name='header',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='zulfiapp.header'),
        ),
    ]
