# Generated by Django 3.1.7 on 2021-02-26 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0006_auto_20210225_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(blank=True, help_text='اضف عنوان رئيسي', max_length=200, null=True, verbose_name='العنوان الرئيسي')),
                ('sub_header', models.TextField(blank=True, help_text='اضف عنوان ثانوي', null=True, verbose_name='الوصف')),
                ('date', models.DateField(default=datetime.datetime(2021, 2, 26, 8, 44, 15, 109979, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'من نحن',
                'verbose_name_plural': 'من نحن',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='zulfiapp.news'),
        ),
    ]
