# Generated by Django 3.1.7 on 2021-02-26 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0007_auto_20210226_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'الأخبار', 'verbose_name_plural': 'الأخبار'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
        migrations.AlterField(
            model_name='image',
            name='header',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='zulfiapp.header'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 8, 53, 48, 28100, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='zulfiapp/static/image')),
                ('news', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='zulfiapp.news')),
            ],
        ),
    ]
