# Generated by Django 3.1.7 on 2021-02-26 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0008_auto_20210226_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hight',
            field=models.CharField(blank=True, choices=[('عرض كبير', 'عرض كبير'), ('عرض عادي', 'عرض عادي ')], help_text='لعرض المحتوى ', max_length=200, null=True, verbose_name='طريقه العرض'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 9, 8, 41, 153890, tzinfo=utc)),
        ),
    ]
