# Generated by Django 3.1.5 on 2021-02-27 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0009_auto_20210226_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 4, 26, 5, 963240, tzinfo=utc)),
        ),
    ]
