# Generated by Django 3.1.5 on 2021-02-27 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zulfiapp', '0011_auto_20210227_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='اضف الفرع', max_length=200, null=True, verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'من نحن',
                'verbose_name_plural': 'من نحن',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 6, 12, 7, 918523, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Image3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='zulfiapp/static/image')),
                ('portfolio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='zulfiapp.ourportfolio')),
            ],
        ),
    ]
